server:
  port: 5000
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/officium
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
